server:
  port: 8081
  #context-path: /h2demo
logging:
  config: classpath:log4j2.xml
spring:
  profiles:
    active: h2
---
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:myh2 #h2数据库的连接地址，这是一个内存数据库
    driverClassName: org.h2.Driver #JDBC Driver
    username: ocean #数据库用户名
    password: 123 #数据库密码
    schema: classpath:db/schema.sql #启动程序后对数据库的结果进行操作
    data: classpath:db/data.sql #启动程序后对数据库的数据进行操作
  h2:
    console:
      enabled: true #启动web console服务，默认地址http://localhost:8080/h2-console
  jpa:
    show_sql: true #查询sql语句在控制台打印
    format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      globally_quoted_identifiers: true
      hbm2ddl:
        auto: update #每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新
